language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - npm run build
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
          - npx semantic-release
